### ISSUE TITLE
Support skimage version >=0.19

### ISSUE THREAD

**Issue by afrendeiro** [javadnoorb/HistCNN#8]
[scikit-image 0.19.0](https://scikit-image.org/docs/dev/release_notes.html?highlight=rgb2grey#id14) replaced `skimge.color.rgb2grey` with `skimge.color.rgb2gray`.

A user must pin the skimage version or update code accordingly.

**Comment by javadnoorb** [comment]
Thanks for reporting this. I just changed the syntax to match the newer version.
